package com.example.petproject2.persistance.entity.DynamoEntity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "products")
public class DynamoProduct {

    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String productId;

    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    List<String> customers = new ArrayList<>();
}
