CREATE TABLE customer
(
    customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);

CREATE TABLE customer_product
(
    customer_id BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_customer_product PRIMARY KEY (customer_id, product_id)
);

CREATE TABLE product
(
    product_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

ALTER TABLE customer_product
    ADD CONSTRAINT FK_CUSTOMER_PRODUCT_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE customer_product
    ADD CONSTRAINT FK_CUSTOMER_PRODUCT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

create sequence bucket_seq start 1 increment 1;

create table buckets (
                         id int8 not null,
                         customer_id int8,
                         primary key (id)
);

-- LINK BETWEEN BUCKET AND USER
alter table if exists buckets
    add constraint buckets_fk_customer
    foreign key (customer_id) references customer;

create table bucket_products (
                                 bucket_id int8 not null,
                                 product_id int8 not null
);

alter table if exists bucket_products
    add constraint bucket_products_fk_product
    foreign key (product_id) references product;

alter table if exists bucket_products
    add constraint bucket_products_fk_bucket
    foreign key (bucket_id) references buckets;