version: "3"
services:
#  sonarqube:
#    image: sonarqube:lts
#    ports:
#      - 9000:9000
#    networks:
#      - mynetwork
#    environment:
#      - SONAR_FORCEAUTHENTICATION=false
#  jenkins:
#    image: jenkins/jenkins:2.319.1-jdk11
#    ports:
#      - 8080:8080
#    networks:
#      - mynetwork
  app1:
    image: 'app'
    build:
      context: .
    container_name: app1
    depends_on:
      - db1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db1:5432/db_pet2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8090:8090
  db1:
    image: 'postgres:13.1-alpine'
    container_name: db1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db_pet2
#networks:
#  mynetwork: