spring:
  datasource:
    url: jdbc:h2:mem:db_pet2;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  flyway:
    clean-disabled: false
    enabled: false

  data:
    mongodb:
      database: dp_pet

server:
  port: 8083

logging:
  file:
    path:
